import os

os.system('pip install --upgrade pip')
os.system('pip install telethon==1.21.1')
from telethon.sync import TelegramClient
from telethon.sessions import StringSession
                                           

a = """
 
"""
print(a)
print(""" USERBOT1 SESSION String StringSession Generated By Team USERBOT1.
Please go to https://my.telegram.org  and get your details."""
      )
print("Enter The Your Values Down")


print("Never Share Your String Session To Anyone Your Account Can be Hacked And can be Misused")
APP_ID = int(input("Enter APP ID - "))
API_HASH = input("Enter API HASH - ")

with TelegramClient(StringSession(), APP_ID, API_HASH) as tb:
    print("")
    print("Below is your STRING_SESSION")
    print("")
    print(tb.session.save())
    print("")
    print("This can be found in your saved messages in telegram too.")
    tele = tb.send_message("me", f"`{tb.session.save()}`")
    tele.reply("The above is the `STRING_SESSION`.\n@TeamUserBot1")
